### ISSUE TITLE
ValueError: empty vocabulary; perhaps the documents only contain stop words---also expect a english version!

### ISSUE THREAD

**Issue by SeekPoint** [TakuyaHiraoka/Active-Learning-for-Example-based-Dialog-Systems#1]

**Comment by SeekPoint** [comment]
rzai@rzai00:~/prj/Active-Learning-for-Example-based-Dialog-Systems$ python ActiveConstructionofExamplBase.py 
オラクルの対話ファイルの読み込み(TouristInfo)
システムが不適切な応答をしている部分の削除
読み込んだ対話データのコンパイル
構築
ユーザ発話のコンパイル
Traceback (most recent call last):
  File "ActiveConstructionofExamplBase.py", line 2941, in <module>
    vectorizorForUserUtterane, compiledUserInput=w2vComp.ConstructCimilarityCalculatorAndTfIDFVectors(dialogs)
  File "ActiveConstructionofExamplBase.py", line 1329, in ConstructCimilarityCalculatorAndTfIDFVectors
    matTfidf=vecotorizerTfidf.fit_transform(dialogues)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/feature_extraction/text.py", line 1332, in fit_transform
    X = super(TfidfVectorizer, self).fit_transform(raw_documents)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/feature_extraction/text.py", line 824, in fit_transform
    self.fixed_vocabulary_)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/feature_extraction/text.py", line 771, in _count_vocab
    raise ValueError("empty vocabulary; perhaps the documents only"
ValueError: empty vocabulary; perhaps the documents only contain stop words
rzai@rzai00:~/prj/Active-Learning-for-Example-based-Dialog-Systems$ 
rzai@rzai00:~/prj/Active-Learning-for-Example-based-Dialog-Systems$ 
rzai@rzai00:~/prj/Active-Learning-for-Example-based-Dialog-Systems$ ll OracleCorpus/
total 44
drwxrwxr-x 11 rzai rzai 4096 11月 17 15:54 ./
drwxrwxr-x  4 rzai rzai 4096 11月 17 15:53 ../
drwxrwxr-x  3 rzai rzai 4096 11月 28  2015 OracleCorpus.bu.BusInfo(DSTC1)/
drwxrwxr-x  2 rzai rzai 4096 11月 28  2015 OracleCorpus.bu.Cleverbot/
drwxrwxr-x 22 rzai rzai 4096 11月 28  2015 OracleCorpus.bu.GuideDomain/
drwxrwxr-x  4 rzai rzai 4096 11月 28  2015 OracleCorpus.bu.IdosMovie/
drwxrwxr-x 17 rzai rzai 4096 11月 28  2015 OracleCorpus.bu.ProjectNextNLP/
drwxrwxr-x  3 rzai rzai 4096 11月 28  2015 OracleCorpus.bu.RestrantInfo(DSTC2)/
drwxrwxr-x 32 rzai rzai 4096 11月 28  2015 OracleCorpus.bu.Switchboard/
drwxrwxr-x  3 rzai rzai 4096 11月 28  2015 OracleCorpus.bu.TouristInfo(DSTC3)/
drwxrwxr-x  2 rzai rzai 4096 11月 28  2015 OracleCorpus.bu.Trains/
rzai@rzai00:~/prj/Active-Learning-for-Example-based-Dialog-Systems$
